name: todo_app
description: "To do app project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  go_router: ^17.1.0
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  formz: ^0.8.0
  dio: ^5.9.1
  freezed: ^3.2.5
  json_annotation: ^4.10.0
  intl: ^0.20.2
  provider: ^6.1.5+1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.11.0
  freezed_annotation: ^3.1.0
  json_serializable: ^6.12.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - .env.example

flutter_intl:
  main_locale: ru
  enabled: true